# syntax=docker/dockerfile:1
ARG RUBY_VERSION=3.4.7
FROM ruby:${RUBY_VERSION}-slim

WORKDIR /rails

# System deps for Rails + common gems + Chromium (for System Tests on ARM/Apple Silicon)
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
      build-essential git libpq-dev libyaml-dev pkg-config curl libvips postgresql-client \
      chromium chromium-driver && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

ENV RAILS_ENV=development \
    BUNDLE_PATH=/usr/local/bundle \
    BUNDLE_WITHOUT=""

# App code
COPY . .

EXPOSE 3000
CMD ["sh", "-c", "bundle check || bundle install && bin/rails server -b 0.0.0.0 -p 3000"]